changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    # authors:
    #   - github-actions
  categories:
    - title: Breaking Change
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Improvements
      labels:
        - improvement
    - title: Bug Fixes
      labels:
        - bug
    - title: Hot Fixes
      labels:
        - hotfix
    # - title: Other Changes
    #   labels:
    #     - "*"
