name: "Auto PR Labeling"
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-pr-labeling:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get label name
        id: label_name
        run: |
          branch_type=$(echo ${{ github.head_ref }} | cut -d "/" -f1)
          if [ $branch_type == 'feature' ]; then
            label_name="feature"
          elif [ $branch_type == 'feat' ]; then
            label_name="feature"
          elif [ $branch_type == 'fix' ]; then
            label_name="bug"
          elif [ $branch_type == 'hotfix' ]; then
            label_name="hotfix"
          else
            label_name=""
          fi
          echo "label_name=$label_name" >> $GITHUB_OUTPUT

      - name: Auto labeling
        if: ${{ steps.label_name.outputs.label_name != '' }}
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
            -d "{\"labels\":[\"${{ steps.label_name.outputs.label_name }}\"]}"
