name: "Generating Release and Changelog"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release-and-changelog:
    # Triggered only when a PR is merged and labeled with `release`
    if: |
      github.event.pull_request.merged == true &&
      (contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: roodolv/release-and-changelog@v1
        env:
          TZ: "Asia/Tokyo"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
